import {PIPES_DECLARATIONS} from './pipes';
import {COMPONENTS_DECLARATIONS, ENTRY_COMPONENTS_DECLARATIONS} from './components';

export const COMPONENTS = [COMPONENTS_DECLARATIONS];
export const ENTRY_COMPONENTS = [ENTRY_COMPONENTS_DECLARATIONS];
export const PIPES = [PIPES_DECLARATIONS];
